//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteSimpressFabio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int ProdutoID { get; set; }
        public string ProdutoNome { get; set; }
        public string ProdutoDescricao { get; set; }
        public Nullable<bool> ProdutoAtivo { get; set; }
        public Nullable<bool> ProdutoPerecivel { get; set; }
        public int ProdutoCategoriaID { get; set; }
    
        public virtual CategoriaProduto CategoriaProduto { get; set; }
    }
}
